---
driver:
  name: vagrant
  username: root
  password: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: bento/centos-7.2

suites:
  - name: default
    run_list:
      - recipe[atop]
    attributes:
      atop:
        interval: 1
